### ISSUE TITLE
Add schematic in pdf too

### ISSUE THREAD

**Issue by mrx23dot** [ElectronicCats/faultycat#3]

**Comment by Marcelol52** [comment]
Hi, we will consider adding the file to the Wiki for later revisions. We cannot add it on the repository because it is not a binnary file and it would not be updated automatically by git. You can always check the schematics usig KiCAD on any operating system from the files found on the hardware section of the repository. I have shared the PDF with you attached in this message. Thank your for your suggestion and your preference. 

[FaultyCat.pdf](https://github.com/ElectronicCats/faultycat/files/14388274/FaultyCat.pdf)
